name = "raid-form"
main = "src/index.js"
compatibility_date = "2026-02-15"

[env.production]
# Add your secrets here later

[vars]
SHEETS_ID = "1NTXywhb6hidda8Kju1_l8GBDLxdzu8sE0MXNOQtgxS4"
SERVICE_ACCOUNT_EMAIL = "raid-form-bot@fluke-gaming.iam.gserviceaccount.com"

[observability]
[observability.logs]
enabled = true
invocation_logs = true